name: Gemini CLI
on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  claude:
    if: contains(github.event.comment.body, '@gemini')
    runs-on: ubuntu-latest
    steps:
      - uses: masahif/gemini-cli-action@main
        # with:
        #   gemini_api_key: ${{ secrets.GEMINI_API_KEY }}